# Generated by Django 3.1.3 on 2020-12-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=6, verbose_name='Número da conta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo')),
            ],
        ),
    ]
